"""
Definiciones de tablas de dimensión del DM_ACADEMICO
"""

# Tablas de dimensión sin dependencias (Fase 1)
DIMENSION_TABLES_PHASE1 = [
    'D_SEXO',
    'D_TIEMPO',
    'D_PAIS',
    'D_TIPO_ESTUDIO',
    'D_RAMA_CONOCIMIENTO',
    'D_CURSO_ACADEMICO',
    'D_CURSO_COHORTE',
    'D_CALIFICACION',
    'D_CONVOCATORIA',
    'D_TIPO_ACCESO',
    'D_TIPO_ACCESO_PREINSCRIPCION',
    'D_TIPO_DOCENCIA',
    'D_TIPO_EGRESO',
    'D_TIPO_ABANDONO',
    'D_TIPO_PROCEDIMIENTO',
    'D_TIPO_RECONOCIMIENTO',
    'D_CUPO_ADJUDICACION',
    'D_ESTADO_ADJUDICACION',
    'D_RANGO_CREDITO',
    'D_RANGO_EDAD',
    'D_RANGO_NOTA_ADMISION',
    'D_RANGO_NOTA_NUMERICA',
    'D_RANGO_NOTA_CRUE',
    'D_RANGO_NOTA_EGRACONS',
    'D_CLASE_ASIGNATURA',
    'D_EDAD_EST',
    'D_ESTUDIO_PREVIO',
    'D_MODALIDAD_PLAN_ESTUDIO',
    'D_IDIOMA_MOVILIDAD',
    'D_NIVEL_ESTUDIOS_MOVILIDAD',
    'D_AREA_ESTUDIOS_MOVILIDAD',
    'D_COLECTIVO_MOVILIDAD',
    'D_ESTADO_ACUERDO_BILATERAL',
    'D_ESTUDIO_PROPIO_TIPO',
    'D_ESTUDIO_PROPIO_MODALIDAD',
    'D_ESTUDIO_PROPIO_ORGANO_GEST',
    'D_DOCTORADO_TIPO_BECA',
    'D_ESTADO_SOLICITUD_DOCTORADO',
    'D_DEDICACION',
    'D_DEDICACION_PROFESOR',
    'D_CATEGORIA_CUERPO_PDI',
    'D_ARTICULO',
    'D_TIPO_ASIGNATURA',
    'D_TIPO_CENTRO',
    'D_CAMPUS',
    'D_RAMA_MACROAREA',
    'D_NACIONALIDAD',
    'D_DETALLE_CUPO_GENERAL',
    'D_CLASE_LIQUIDACION',
    # Nuevas dimensiones básicas (Fase 1)
    'D_ESTADO_CREDENCIAL_ACCESO',
    'D_NIVEL_IDIOMA',
    'D_SITUACION_ADMINISTRATIVA',
    'D_TIPO_CONTRATO',
    'D_MODALIDAD_ASIGNATURA',
    'D_PERIODO_LECTIVO',
    'D_AREA_CONOCIMIENTO',
    'D_TIPO_INSCRIPCION',
    'D_AMBITO_CONOCIMIENTO',
    'D_EVENTO_ACADEMICO',
    'D_DEDICACION_ALUMNO',
]

# Tablas de dimensión con dependencias (Fase 2)
DIMENSION_TABLES_PHASE2 = [
    'D_POBLACION',  # Depende de D_PAIS
    'D_POBLACION_CENTRO',  # Depende de D_POBLACION
    'D_CENTRO',  # Depende de D_POBLACION, D_TIPO_CENTRO, D_CAMPUS
    'D_UNIVERSIDAD',  # Depende de D_PAIS
    'D_CENTRO_DESTINO',  # Depende de D_UNIVERSIDAD
    'D_CENTRO_OTRA_UNIVERSIDAD',  # Depende de D_UNIVERSIDAD
    'D_PERSONA',  # Depende de D_PAIS
    'D_TITULACION',  # Depende de D_TIPO_TITULACION
    'D_ESTUDIO',  # Independiente
    'D_PLAN_ESTUDIO',  # Independiente
    'D_ESTUDIO_JERARQ',  # Depende de D_PLAN_ESTUDIO, D_ESTUDIO, D_TIPO_ESTUDIO, D_RAMA_CONOCIMIENTO
    'D_ESTUDIO_DESTINO',  # Independiente
    'D_ESTUDIO_OTRA_UNIVERSIDAD',  # Depende de D_ESTUDIO_DESTINO
    'D_ASIGNATURA',  # Independiente
    'D_PLAN_ESTUDIO_ASIGNATURA',  # Depende de D_ASIGNATURA, D_PLAN_ESTUDIO, D_CLASE_ASIGNATURA
    'D_PLAN_ESTUDIO_ANO_DATOS',  # Depende de D_CURSO_COHORTE, D_PLAN_ESTUDIO, D_TIPO_ESTUDIO, D_MODALIDAD_PLAN_ESTUDIO
    'D_CENTRO_ESTUDIO',  # Depende de D_UNIVERSIDAD, D_CENTRO, D_PLAN_ESTUDIO
    'D_GRUPO',  # Depende de D_CURSO_COHORTE, D_CENTRO, D_ASIGNATURA
    'D_IDIOMA_NIVEL_MOVILIDAD',  # Depende de D_IDIOMA_MOVILIDAD
    'D_PROGRAMA_MOVILIDAD',  # Independiente
    'D_ESTUDIO_PROPIO',  # Depende de D_ESTUDIO_PROPIO_TIPO
    'D_ACUERDO_BILATERAL',  # Independiente
    'D_PROYECTO_INVESTIGACION',  # Independiente
    'D_RANGO_CREDITO_MOVILIDAD',  # Depende de D_RANGO_CREDITO
    'D_CONVOCATORIA_PREINSCRIPCION',  # Depende de D_CONVOCATORIA
    'D_TERRITORIO',  # Depende de D_PAIS
    'D_ASIGNATURA_ORIGEN',  # Depende de D_ASIGNATURA
]

# Todas las tablas de dimensión
DIMENSION_TABLES = DIMENSION_TABLES_PHASE1 + DIMENSION_TABLES_PHASE2

# Mapeo de tablas a volúmenes de datos
TABLE_VOLUMES = {
    # Tablas pequeñas (menos de 100 registros)
    'D_SEXO': 2,
    'D_CURSO_ACADEMICO': 15,
    'D_CURSO_COHORTE': 15,
    'D_CALIFICACION': 10,
    'D_CONVOCATORIA': 5,
    'D_TIPO_ACCESO': 15,
    'D_TIPO_ACCESO_PREINSCRIPCION': 15,
    'D_TIPO_DOCENCIA': 5,
    'D_TIPO_EGRESO': 5,
    'D_TIPO_ABANDONO': 5,
    'D_TIPO_PROCEDIMIENTO': 5,
    'D_TIPO_RECONOCIMIENTO': 5,
    'D_CUPO_ADJUDICACION': 10,
    'D_ESTADO_ADJUDICACION': 5,
    'D_RANGO_CREDITO': 10,
    'D_RANGO_EDAD': 10,
    'D_RANGO_NOTA_ADMISION': 10,
    'D_RANGO_NOTA_NUMERICA': 10,
    'D_RANGO_NOTA_CRUE': 10,
    'D_RANGO_NOTA_EGRACONS': 10,
    'D_CLASE_ASIGNATURA': 5,
    'D_EDAD_EST': 10,
    'D_TIPO_ESTUDIO': 10,
    'D_RAMA_CONOCIMIENTO': 10,
    'D_ESTUDIO_PREVIO': 20,
    'D_MODALIDAD_PLAN_ESTUDIO': 5,
    'D_IDIOMA_MOVILIDAD': 20,
    'D_NIVEL_ESTUDIOS_MOVILIDAD': 5,
    'D_AREA_ESTUDIOS_MOVILIDAD': 30,
    'D_COLECTIVO_MOVILIDAD': 5,
    'D_ESTADO_ACUERDO_BILATERAL': 5,
    'D_ESTUDIO_PROPIO_TIPO': 10,
    'D_ESTUDIO_PROPIO_MODALIDAD': 5,
    'D_ESTUDIO_PROPIO_ORGANO_GEST': 10,
    'D_DOCTORADO_TIPO_BECA': 10,
    'D_ESTADO_SOLICITUD_DOCTORADO': 5,
    'D_DEDICACION': 5,
    'D_DEDICACION_PROFESOR': 5,
    'D_CATEGORIA_CUERPO_PDI': 20,
    'D_TIPO_ASIGNATURA': 10,
    'D_TIPO_CENTRO': 5,
    'D_CAMPUS': 10,
    'D_RAMA_MACROAREA': 15,
    'D_NACIONALIDAD': 200,
    'D_DETALLE_CUPO_GENERAL': 10,
    'D_CLASE_LIQUIDACION': 10,
    'D_TIEMPO': 3650,  # 10 años x 365 días
    'D_IDIOMA_NIVEL_MOVILIDAD': 40,  # 20 idiomas x 2 niveles promedio
    'D_RANGO_CREDITO_MOVILIDAD': 10,
    'D_CONVOCATORIA_PREINSCRIPCION': 5,
    # Nuevas dimensiones
    'D_ESTADO_CREDENCIAL_ACCESO': 5,
    'D_NIVEL_IDIOMA': 10,
    'D_SITUACION_ADMINISTRATIVA': 10,
    'D_TIPO_CONTRATO': 15,
    'D_MODALIDAD_ASIGNATURA': 5,
    'D_PERIODO_LECTIVO': 8,
    'D_AREA_CONOCIMIENTO': 50,
    'D_TIPO_INSCRIPCION': 10,
    'D_AMBITO_CONOCIMIENTO': 40,
    'D_EVENTO_ACADEMICO': 30,
    'D_DEDICACION_ALUMNO': 5,
    'D_ASIGNATURA_ORIGEN': 200,
    'D_TERRITORIO': 100,
    
    # Tablas medianas (100-1000 registros)
    'D_PAIS': 200,
    'D_POBLACION': 500,
    'D_POBLACION_CENTRO': 300,
    'D_CENTRO': 100,
    'D_UNIVERSIDAD': 300,
    'D_CENTRO_DESTINO': 500,
    'D_CENTRO_OTRA_UNIVERSIDAD': 500,
    'D_TITULACION': 200,
    'D_ESTUDIO': 300,
    'D_PLAN_ESTUDIO': 500,
    'D_ESTUDIO_JERARQ': 300,
    'D_ESTUDIO_DESTINO': 200,
    'D_ESTUDIO_OTRA_UNIVERSIDAD': 200,
    'D_CENTRO_ESTUDIO': 200,
    'D_PROGRAMA_MOVILIDAD': 50,
    'D_ESTUDIO_PROPIO': 100,
    'D_ACUERDO_BILATERAL': 300,
    'D_PROYECTO_INVESTIGACION': 200,
    'D_ARTICULO': 500,
    
    # Tablas grandes (más de 1000 registros)
    'D_PERSONA': 10000,
    'D_ASIGNATURA': 2000,
    'D_PLAN_ESTUDIO_ASIGNATURA': 5000,
    'D_PLAN_ESTUDIO_ANO_DATOS': 1500,
    'D_GRUPO': 3000,
}

# Dependencias entre tablas (tabla_dependiente: [tabla_de_la_que_depende])
TABLE_DEPENDENCIES = {
    'D_POBLACION': ['D_PAIS'],
    'D_POBLACION_CENTRO': ['D_POBLACION'],
    'D_CENTRO': ['D_POBLACION', 'D_TIPO_CENTRO', 'D_CAMPUS'],
    'D_UNIVERSIDAD': ['D_PAIS'],
    'D_CENTRO_DESTINO': ['D_UNIVERSIDAD'],
    'D_CENTRO_OTRA_UNIVERSIDAD': ['D_UNIVERSIDAD'],
    'D_PERSONA': ['D_PAIS'],
    'D_ESTUDIO_JERARQ': ['D_PLAN_ESTUDIO', 'D_ESTUDIO', 'D_TIPO_ESTUDIO', 'D_RAMA_CONOCIMIENTO'],
    'D_ESTUDIO_OTRA_UNIVERSIDAD': ['D_ESTUDIO_DESTINO'],
    'D_PLAN_ESTUDIO_ASIGNATURA': ['D_ASIGNATURA', 'D_PLAN_ESTUDIO', 'D_CLASE_ASIGNATURA'],
    'D_PLAN_ESTUDIO_ANO_DATOS': ['D_CURSO_COHORTE', 'D_PLAN_ESTUDIO', 'D_TIPO_ESTUDIO', 'D_MODALIDAD_PLAN_ESTUDIO'],
    'D_CENTRO_ESTUDIO': ['D_UNIVERSIDAD', 'D_CENTRO', 'D_PLAN_ESTUDIO'],
    'D_GRUPO': ['D_CURSO_COHORTE', 'D_CENTRO', 'D_ASIGNATURA'],
    'D_IDIOMA_NIVEL_MOVILIDAD': ['D_IDIOMA_MOVILIDAD'],
    'D_RANGO_CREDITO_MOVILIDAD': ['D_RANGO_CREDITO'],
    'D_CONVOCATORIA_PREINSCRIPCION': ['D_CONVOCATORIA'],
    'D_TERRITORIO': ['D_PAIS'],
    'D_ASIGNATURA_ORIGEN': ['D_ASIGNATURA'],
}

# Columnas que deben ser únicas por tabla
UNIQUE_COLUMNS = {
    'D_PAIS': ['ID_PAIS_NK'],
    'D_PERSONA': ['ID_PERSONA_NIP_NK', 'DOCUMENTO_IDENTIDAD'],
    'D_SEXO': ['ID_SEXO_NK'],
    'D_CALIFICACION': ['ID_CALIFICACION_NK'],
    'D_TIPO_ACCESO': ['ID_TIPO_ACCESO_NK'],
    'D_ESTUDIO_PREVIO': ['ID_ESTUDIO_PREVIO_NK'],
    'D_CUPO_ADJUDICACION': ['ID_CUPO_ADJUDICACION_NK'],
    'D_CURSO_ACADEMICO': ['ID_CURSO_ACADEMICO_NK'],
    'D_CURSO_COHORTE': ['ID_CURSO_ACADEMICO_NK'],
    'D_RANGO_CREDITO': ['ID_RANGO_CREDITO_NK'],
    'D_RANGO_EDAD': ['ID_RANGO_EDAD_NK'],
    'D_RANGO_NOTA_ADMISION': ['ID_RANGO_NOTA_ADMISION_NK'],
    'D_RANGO_NOTA_NUMERICA': ['ID_RANGO_NOTA_NUMERICA_NK'],
    'D_RANGO_NOTA_CRUE': ['ID_RANGO_NOTA_CRUE_NK'],
    'D_RANGO_NOTA_EGRACONS': ['ID_RANGO_NOTA_EGRACONS_NK'],
    'D_CLASE_ASIGNATURA': ['ID_CLASE_ASIGNATURA_NK'],
    'D_TIPO_RECONOCIMIENTO': ['ID_TIPO_RECONOCIMIENTO_NK'],
    'D_UNIVERSIDAD': ['ID_UNIVERSIDAD_NK'],
    'D_CENTRO': ['ID_CENTRO_NK'],
    'D_ASIGNATURA': ['ID_ASIGNATURA_NK'],
    'D_PLAN_ESTUDIO': ['ID_PLAN_ESTUDIO_NK'],
    'D_ESTUDIO': ['ID_ESTUDIO_NK'],
    'D_ESTUDIO_DESTINO': ['ID_ESTUDIO_OTRA_UNIVERSIDAD_NK'],
    'D_ESTUDIO_OTRA_UNIVERSIDAD': ['ID_ESTUDIO_OTRA_UNIVERSIDAD_NK'],
    'D_CENTRO_DESTINO': ['ID_CENTRO_OTRA_UNIVERSIDAD_NK'],
    'D_CENTRO_OTRA_UNIVERSIDAD': ['ID_CENTRO_OTRA_UNIVERSIDAD_NK'],
    'D_GRUPO': ['ID_GRUPO_NK'],
    'D_MODALIDAD_PLAN_ESTUDIO': ['ID_MODALIDAD_PLAN_ESTUDIO_NK'],
    'D_IDIOMA_MOVILIDAD': ['ID_IDIOMA_MOVILIDAD_NK'],
    'D_NIVEL_ESTUDIOS_MOVILIDAD': ['ID_NIVEL_ESTUDIOS_MOVILIDAD_NK'],
    'D_AREA_ESTUDIOS_MOVILIDAD': ['ID_AREA_ESTUDIOS_MOVILIDAD_NK'],
    'D_COLECTIVO_MOVILIDAD': ['ID_COLECTIVO_MOVILIDAD_NK'],
    'D_ESTADO_ACUERDO_BILATERAL': ['ID_ESTADO_ACUERDO_NK'],
    'D_ESTUDIO_PROPIO': ['ID_ESTUDIO_PROPIO_NK'],
    'D_ESTUDIO_PROPIO_TIPO': ['ID_ESTUDIO_PROPIO_TIPO_NK'],
    'D_ESTUDIO_PROPIO_MODALIDAD': ['ID_ESTUDIO_PROPIO_MODALIDAD_NK'],
    'D_ESTUDIO_PROPIO_ORGANO_GEST': ['ID_ORGANO_GESTION_EP_NK'],
    'D_DOCTORADO_TIPO_BECA': ['ID_TIPO_BECA_NK'],
    'D_ESTADO_SOLICITUD_DOCTORADO': ['ID_ESTADO_SOL_DOCTORADO_NK'],
    'D_DEDICACION': ['ID_DEDICACION_NK'],
    'D_DEDICACION_PROFESOR': ['ID_DEDICACION_NK'],
    'D_CATEGORIA_CUERPO_PDI': ['ID_CATEGORIA_CUERPO_ESCALA'],
    'D_TIPO_ASIGNATURA': ['ID_TIPO_ASIGNATURA_NK'],
    'D_TIPO_CENTRO': ['ID_TIPO_CENTRO'],
    'D_CAMPUS': ['ID_CAMPUS'],
    'D_RAMA_MACROAREA': ['ID_RAMA_CONOCIMIENTO_NK', 'ID_MACROAREA_NK'],
    'D_NACIONALIDAD': ['ID_NACIONALIDAD'],
    'D_DETALLE_CUPO_GENERAL': ['ID_DETALLE_CUPO_GENERAL_NK'],
    'D_CLASE_LIQUIDACION': ['ID_CLASE_LIQUIDACION_NK'],
    'D_PROGRAMA_MOVILIDAD': ['ID_PROGRAMA_MOVILIDAD_NK'],
    'D_ACUERDO_BILATERAL': ['ID_ACUERDO_BILATERAL_NK'],
    'D_PROYECTO_INVESTIGACION': ['ID_PROYECTO_INVESTIGACION_NK'],
    # Nuevas dimensiones
    'D_ESTADO_CREDENCIAL_ACCESO': ['ID_ESTADO_CREDENCIAL_ACCESO_NK'],
    'D_NIVEL_IDIOMA': ['ID_NIVEL_IDIOMA_NK'],
    'D_SITUACION_ADMINISTRATIVA': ['ID_SITUACION_ADMINISTRATIVA_NK'],
    'D_TIPO_CONTRATO': ['ID_TIPO_CONTRATO_NK'],
    'D_MODALIDAD_ASIGNATURA': ['ID_MODALIDAD_ASIGNATURA_NK'],
    'D_PERIODO_LECTIVO': ['ID_PERIODO_LECTIVO_NK'],
    'D_AREA_CONOCIMIENTO': ['ID_AREA_CONOCIMIENTO_NK'],
    'D_TIPO_INSCRIPCION': ['ID_TIPO_INSCRIPCION_NK'],
    'D_AMBITO_CONOCIMIENTO': ['ID_AMBITO_CONOCIMIENTO_NK'],
    'D_EVENTO_ACADEMICO': ['ID_EVENTO_ACADEMICO_NK'],
    'D_DEDICACION_ALUMNO': ['ID_DEDICACION_ALUMNO_NK'],
    'D_ASIGNATURA_ORIGEN': ['ID_ASIGNATURA_ORIGEN_NK'],
    'D_TERRITORIO': ['ID_TERRITORIO_NK'],
} 