"""
Definiciones de tablas de hechos del DM_ACADEMICO
"""

# Lista de tablas de hechos
FACT_TABLES = [
    'F_COHORTE',
    'F_DOCTORADO',
    'F_DOCTORADO_ADMISION',
    'F_EGRACONS',
    'F_EGRESADO',
    'F_ESTUDIANTES_MOVILIDAD_IN',
    'F_ESTUDIANTES_MOVILIDAD_OUT',
    'F_ESTUDIO_PROPIO_MATRICULA',
    'F_MATRICULA',
    'F_OFERTA_ACUERDO_BILATERAL',
    'F_OFERTA_ADMISION',
    'F_RENDIMIENTO',
    'F_SOLICITANTE_ADMISION',
    'F_SOLICITUDES_MOVILIDAD',
    'F_TABLA_FUSION',
    'F_TABLA_FUSION_ESTCEN',
]

# Estado de implementación de cada tabla de hechos
FACT_TABLES_IMPLEMENTATION_STATUS = {
    'F_MATRICULA': 'COMPLETA',      # Implementada completamente
    'F_RENDIMIENTO': 'COMPLETA',    # Implementada completamente
    'F_COHORTE': 'NO IMPLEMENTADA',
    'F_DOCTORADO': 'NO IMPLEMENTADA',
    'F_DOCTORADO_ADMISION': 'NO IMPLEMENTADA',
    'F_EGRACONS': 'NO IMPLEMENTADA',
    'F_EGRESADO': 'NO IMPLEMENTADA',
    'F_ESTUDIANTES_MOVILIDAD_IN': 'NO IMPLEMENTADA',
    'F_ESTUDIANTES_MOVILIDAD_OUT': 'NO IMPLEMENTADA',
    'F_ESTUDIO_PROPIO_MATRICULA': 'NO IMPLEMENTADA',
    'F_OFERTA_ACUERDO_BILATERAL': 'NO IMPLEMENTADA',
    'F_OFERTA_ADMISION': 'NO IMPLEMENTADA',
    'F_SOLICITANTE_ADMISION': 'NO IMPLEMENTADA',
    'F_SOLICITUDES_MOVILIDAD': 'NO IMPLEMENTADA',
    'F_TABLA_FUSION': 'NO IMPLEMENTADA',
    'F_TABLA_FUSION_ESTCEN': 'NO IMPLEMENTADA',
}

# Número total de atributos por tabla de hechos
FACT_TABLE_ATTRIBUTES = {
    'F_MATRICULA': 86,        # Implementados parcialmente
    'F_RENDIMIENTO': 81,      # Implementados parcialmente
    'F_COHORTE': 69,          # No implementados
    'F_DOCTORADO': 138,       # No implementados
    'F_DOCTORADO_ADMISION': 41,  # No implementados
    'F_EGRACONS': 45,         # No implementados
    'F_EGRESADO': 101,        # No implementados
    'F_ESTUDIANTES_MOVILIDAD_IN': 45,  # No implementados
    'F_ESTUDIANTES_MOVILIDAD_OUT': 57, # No implementados
    'F_ESTUDIO_PROPIO_MATRICULA': 73,  # No implementados
    'F_OFERTA_ACUERDO_BILATERAL': 45,  # No implementados
    'F_OFERTA_ADMISION': 51,  # No implementados
    'F_SOLICITANTE_ADMISION': 69,  # No implementados
    'F_SOLICITUDES_MOVILIDAD': 43,  # No implementados
    'F_TABLA_FUSION': 17,     # No implementados
    'F_TABLA_FUSION_ESTCEN': 38,  # No implementados
}

# Volumen de datos para cada tabla de hechos
FACT_TABLE_VOLUMES = {
    'F_COHORTE': 20000,
    'F_DOCTORADO': 5000,
    'F_DOCTORADO_ADMISION': 2000,
    'F_EGRACONS': 10000,
    'F_EGRESADO': 15000,
    'F_ESTUDIANTES_MOVILIDAD_IN': 3000,
    'F_ESTUDIANTES_MOVILIDAD_OUT': 3000,
    'F_ESTUDIO_PROPIO_MATRICULA': 5000,
    'F_MATRICULA': 50000,
    'F_OFERTA_ACUERDO_BILATERAL': 2000,
    'F_OFERTA_ADMISION': 5000,
    'F_RENDIMIENTO': 100000,
    'F_SOLICITANTE_ADMISION': 30000,
    'F_SOLICITUDES_MOVILIDAD': 8000,
    'F_TABLA_FUSION': 1000,
    'F_TABLA_FUSION_ESTCEN': 1000,
}

# Dependencias entre tablas de hechos y dimensiones
FACT_TABLE_DEPENDENCIES = {
    'F_COHORTE': [
        'D_CURSO_COHORTE', 'D_PLAN_ESTUDIO', 'D_CENTRO', 'D_TIPO_ACCESO',
        'D_SEXO', 'D_TIPO_ABANDONO', 'D_ESTUDIO_PREVIO', 'D_PAIS', 'D_POBLACION'
    ],
    'F_DOCTORADO': [
        'D_CURSO_COHORTE', 'D_CENTRO', 'D_PLAN_ESTUDIO', 'D_ASIGNATURA',
        'D_CALIFICACION', 'D_TIPO_BECA', 'D_PROYECTO_INVESTIGACION'
    ],
    'F_DOCTORADO_ADMISION': [
        'D_CURSO_COHORTE', 'D_PLAN_ESTUDIO', 'D_CENTRO', 'D_ESTADO_SOLICITUD_DOCTORADO',
        'D_DEDICACION'
    ],
    'F_EGRACONS': [
        'D_CURSO_ACADEMICO', 'D_PLAN_ESTUDIO', 'D_CENTRO', 'D_POBLACION',
        'D_ASIGNATURA', 'D_CLASE_ASIGNATURA', 'D_CALIFICACION', 'D_RANGO_NOTA_NUMERICA',
        'D_RANGO_NOTA_EGRACONS', 'D_PROGRAMA_MOVILIDAD'
    ],
    'F_EGRESADO': [
        'D_CURSO_COHORTE', 'D_CURSO_ACADEMICO', 'D_TIPO_ABANDONO', 'D_TIPO_EGRESO',
        'D_PLAN_ESTUDIO', 'D_CENTRO', 'D_TIPO_ACCESO', 'D_TITULACION', 'D_POBLACION',
        'D_SEXO', 'D_PAIS', 'D_ESTUDIO_PREVIO'
    ],
    'F_ESTUDIANTES_MOVILIDAD_IN': [
        'D_CURSO_COHORTE', 'D_CURSO_ACADEMICO', 'D_CENTRO', 'D_PLAN_ESTUDIO',
        'D_PAIS', 'D_RANGO_CREDITO', 'D_SEXO', 'D_PROGRAMA_MOVILIDAD'
    ],
    'F_ESTUDIANTES_MOVILIDAD_OUT': [
        'D_CURSO_COHORTE', 'D_CURSO_ACADEMICO', 'D_CENTRO', 'D_PLAN_ESTUDIO',
        'D_PAIS', 'D_TIPO_ACCESO', 'D_RANGO_CREDITO', 'D_SEXO', 'D_RANGO_NOTA_ADMISION',
        'D_POBLACION', 'D_PROGRAMA_MOVILIDAD'
    ],
    'F_ESTUDIO_PROPIO_MATRICULA': [
        'D_CURSO_COHORTE', 'D_CURSO_ACADEMICO', 'D_PERSONA', 'D_ESTUDIO_PROPIO',
        'D_ESTUDIO_PROPIO_TIPO', 'D_ESTUDIO_PROPIO_MODALIDAD', 'D_CENTRO', 'D_PAIS',
        'D_POBLACION', 'D_SEXO'
    ],
    'F_MATRICULA': [
        'D_CURSO_COHORTE', 'D_CURSO_ACADEMICO', 'D_PLAN_ESTUDIO', 'D_CENTRO',
        'D_PAIS', 'D_ASIGNATURA', 'D_CLASE_ASIGNATURA', 'D_TIPO_ACCESO',
        'D_POBLACION', 'D_SEXO', 'D_ESTUDIO_PREVIO', 'D_GRUPO'
    ],
    'F_OFERTA_ACUERDO_BILATERAL': [
        'D_CURSO_COHORTE', 'D_CURSO_ACADEMICO', 'D_AREA_ESTUDIOS_MOVILIDAD',
        'D_NIVEL_ESTUDIOS_MOVILIDAD', 'D_PAIS', 'D_COLECTIVO_MOVILIDAD',
        'D_PROGRAMA_MOVILIDAD', 'D_CENTRO'
    ],
    'F_OFERTA_ADMISION': [
        'D_CURSO_ACADEMICO', 'D_PLAN_ESTUDIO', 'D_CENTRO', 'D_TIPO_ACCESO',
        'D_ESTUDIO_PREVIO', 'D_CUPO_ADJUDICACION', 'D_CURSO_COHORTE', 'D_POBLACION'
    ],
    'F_RENDIMIENTO': [
        'D_CURSO_COHORTE', 'D_CURSO_ACADEMICO', 'D_ASIGNATURA', 'D_CONVOCATORIA',
        'D_PLAN_ESTUDIO', 'D_CENTRO', 'D_TIPO_ACCESO', 'D_GRUPO', 'D_TIPO_DOCENCIA',
        'D_CLASE_ASIGNATURA', 'D_TIPO_RECONOCIMIENTO', 'D_CALIFICACION', 'D_RANGO_NOTA_NUMERICA',
        'D_SEXO', 'D_PAIS', 'D_POBLACION', 'D_RANGO_NOTA_ADMISION', 'D_ESTUDIO_PREVIO'
    ],
    'F_SOLICITANTE_ADMISION': [
        'D_CURSO_ACADEMICO', 'D_CONVOCATORIA', 'D_TIPO_ACCESO_PREINSCRIPCION',
        'D_TIPO_PROCEDIMIENTO', 'D_ESTUDIO_PREVIO', 'D_UNIVERSIDAD', 'D_CUPO_ADJUDICACION',
        'D_PLAN_ESTUDIO', 'D_PERSONA', 'D_SEXO', 'D_POBLACION', 'D_PAIS',
        'D_CENTRO', 'D_ESTADO_ADJUDICACION', 'D_CURSO_COHORTE', 'D_RANGO_NOTA_ADMISION'
    ],
    'F_SOLICITUDES_MOVILIDAD': [
        'D_CURSO_COHORTE', 'D_CURSO_ACADEMICO', 'D_PAIS', 'D_SEXO', 'D_PLAN_ESTUDIO',
        'D_CENTRO', 'D_TIPO_ACCESO', 'D_AREA_ESTUDIOS_MOVILIDAD', 'D_NIVEL_ESTUDIOS_MOVILIDAD',
        'D_IDIOMA_MOVILIDAD', 'D_RANGO_NOTA_ADMISION', 'D_RANGO_CREDITO', 'D_POBLACION',
        'D_PROGRAMA_MOVILIDAD'
    ],
    'F_TABLA_FUSION': [
        'D_CURSO_ACADEMICO', 'D_PLAN_ESTUDIO'
    ],
    'F_TABLA_FUSION_ESTCEN': [
        'D_CURSO_ACADEMICO', 'D_CENTRO'
    ],
}

# Atributos que faltan implementar en las tablas de hechos parcialmente implementadas
MISSING_ATTRIBUTES = {
    'F_MATRICULA': [],  # Todos los atributos implementados
    'F_RENDIMIENTO': []  # Todos los atributos implementados
} 