services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle_db
    environment:
      - ORACLE_PWD=YourStrongPassword123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    shm_size: '2gb'
    restart: unless-stopped

volumes:
  oracle_data: