-- Create Common user (must be created from CDB root)
-- First, ensure we're in the CDB root
ALTER SESSION SET CONTAINER = CDB$ROOT;

-- Drop user if exists (to handle re-runs)
BEGIN
    EXECUTE IMMEDIATE 'DROP USER C##DM_ACADEMICO CASCADE';
    DBMS_OUTPUT.PUT_LINE('User C##DM_ACADEMICO dropped successfully');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1918 THEN
            DBMS_OUTPUT.PUT_LINE('User C##DM_ACADEMICO does not exist, proceeding with creation');
        ELSE
            RAISE;
        END IF;
END;
/

-- Create the Common user C##DM_ACADEMICO
CREATE USER C##DM_ACADEMICO IDENTIFIED BY YourPassword123 CONTAINER=ALL;

-- Grant system privileges
GRANT CREATE SESSION TO C##DM_ACADEMICO CONTAINER=ALL;
GRANT CONNECT TO C##DM_ACADEMICO CONTAINER=ALL;
GRANT RESOURCE TO C##DM_ACADEMICO CONTAINER=ALL;
GRANT DBA TO C##DM_ACADEMICO CONTAINER=ALL;

-- Switch to the PDB to set tablespace and quotas
ALTER SESSION SET CONTAINER = XEPDB1;

-- Set default tablespace in the PDB
ALTER USER C##DM_ACADEMICO DEFAULT TABLESPACE DMACADEMICO_DAT;
ALTER USER C##DM_ACADEMICO QUOTA UNLIMITED ON DMACADEMICO_DAT;

-- Grant additional PDB-specific privileges
GRANT CREATE TABLE TO C##DM_ACADEMICO;
GRANT CREATE VIEW TO C##DM_ACADEMICO;
GRANT CREATE PROCEDURE TO C##DM_ACADEMICO;
GRANT CREATE SEQUENCE TO C##DM_ACADEMICO;
GRANT CREATE SYNONYM TO C##DM_ACADEMICO;

EXIT;
