
-- ============================================
-- SCRIPT PARA COPIAR DATOS DE XEPDB1 A CDB
-- ============================================
-- NOTA: Esta es la versión LEGACY que copia físicamente los datos.
-- Para una solución más eficiente con database links, use:
-- - setup_saiku_cdb_links.sql (configuración con database links)
-- - setup_saiku_cdb.ps1 (script automatizado)
-- ============================================

-- PASO 1: Crear usuario común en CDB (ejecutar como SYSTEM)
CONNECT system/password@localhost:1521/XE

-- Crear usuario común (prefijo C## obligatorio)
CREATE USER C##DM_ACADEMICO IDENTIFIED BY dm_academico CONTAINER=ALL;

-- Otorgar permisos necesarios
GRANT CONNECT, RESOURCE TO C##DM_ACADEMICO CONTAINER=ALL;
GRANT CREATE DATABASE LINK TO C##DM_ACADEMICO CONTAINER=ALL;
GRANT UNLIMITED TABLESPACE TO C##DM_ACADEMICO CONTAINER=ALL;
GRANT CREATE VIEW TO C##DM_ACADEMICO CONTAINER=ALL;

-- PASO 2: Conectar a XEPDB1 y crear database link
CONNECT dm_academico/dm_academico@localhost:1521/XEPDB1

-- Crear database link al CDB
CREATE DATABASE LINK CDB_LINK 
CONNECT TO C##DM_ACADEMICO IDENTIFIED BY dm_academico
USING 'localhost:1521/XE';

-- Probar conexión del link
SELECT * FROM DUAL@CDB_LINK;

-- PASO 3: Copiar tablas dimensionales
PROMPT Copiando tabla D_CURSO_ACADEMICO...
CREATE TABLE D_CURSO_ACADEMICO_TEMP AS SELECT * FROM D_CURSO_ACADEMICO;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE C##DM_ACADEMICO.D_CURSO_ACADEMICO@CDB_LINK';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE C##DM_ACADEMICO.D_CURSO_ACADEMICO@CDB_LINK AS 
SELECT * FROM D_CURSO_ACADEMICO;

PROMPT Copiando tabla D_CENTRO...
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE C##DM_ACADEMICO.D_CENTRO@CDB_LINK';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE C##DM_ACADEMICO.D_CENTRO@CDB_LINK AS 
SELECT * FROM D_CENTRO;

PROMPT Copiando tabla D_ASIGNATURA...
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE C##DM_ACADEMICO.D_ASIGNATURA@CDB_LINK';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE C##DM_ACADEMICO.D_ASIGNATURA@CDB_LINK AS 
SELECT * FROM D_ASIGNATURA;

PROMPT Copiando tabla D_SEXO...
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE C##DM_ACADEMICO.D_SEXO@CDB_LINK';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE C##DM_ACADEMICO.D_SEXO@CDB_LINK AS 
SELECT * FROM D_SEXO;

PROMPT Copiando tabla F_MATRICULA...
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE C##DM_ACADEMICO.F_MATRICULA@CDB_LINK';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE C##DM_ACADEMICO.F_MATRICULA@CDB_LINK AS 
SELECT * FROM F_MATRICULA;

-- Copiar tabla F_RENDIMIENTO si existe
PROMPT Copiando tabla F_RENDIMIENTO (si existe)...
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE C##DM_ACADEMICO.F_RENDIMIENTO@CDB_LINK';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists 
    FROM USER_TABLES 
    WHERE TABLE_NAME = 'F_RENDIMIENTO';

    IF table_exists > 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE C##DM_ACADEMICO.F_RENDIMIENTO@CDB_LINK AS SELECT * FROM F_RENDIMIENTO';
        DBMS_OUTPUT.PUT_LINE('F_RENDIMIENTO copiada exitosamente');
    ELSE
        DBMS_OUTPUT.PUT_LINE('F_RENDIMIENTO no existe, saltando...');
    END IF;
END;
/

-- PASO 4: Verificar copia de datos
PROMPT Verificando copia de datos...
SELECT 'D_CURSO_ACADEMICO' AS TABLA, COUNT(*) AS REGISTROS FROM C##DM_ACADEMICO.D_CURSO_ACADEMICO@CDB_LINK
UNION ALL
SELECT 'D_CENTRO' AS TABLA, COUNT(*) AS REGISTROS FROM C##DM_ACADEMICO.D_CENTRO@CDB_LINK
UNION ALL
SELECT 'D_ASIGNATURA' AS TABLA, COUNT(*) AS REGISTROS FROM C##DM_ACADEMICO.D_ASIGNATURA@CDB_LINK
UNION ALL
SELECT 'D_SEXO' AS TABLA, COUNT(*) AS REGISTROS FROM C##DM_ACADEMICO.D_SEXO@CDB_LINK
UNION ALL
SELECT 'F_MATRICULA' AS TABLA, COUNT(*) AS REGISTROS FROM C##DM_ACADEMICO.F_MATRICULA@CDB_LINK;

-- PASO 5: Crear índices en CDB para mejor rendimiento
PROMPT Creando índices en CDB...
BEGIN
    -- Índices para F_MATRICULA
    EXECUTE IMMEDIATE 'CREATE INDEX C##DM_ACADEMICO.IDX_F_MATRICULA_CURSO@CDB_LINK ON C##DM_ACADEMICO.F_MATRICULA@CDB_LINK(ID_CURSO_ACADEMICO)';
    EXECUTE IMMEDIATE 'CREATE INDEX C##DM_ACADEMICO.IDX_F_MATRICULA_CENTRO@CDB_LINK ON C##DM_ACADEMICO.F_MATRICULA@CDB_LINK(ID_CENTRO)';
    EXECUTE IMMEDIATE 'CREATE INDEX C##DM_ACADEMICO.IDX_F_MATRICULA_ASIG@CDB_LINK ON C##DM_ACADEMICO.F_MATRICULA@CDB_LINK(ID_ASIGNATURA)';
    EXECUTE IMMEDIATE 'CREATE INDEX C##DM_ACADEMICO.IDX_F_MATRICULA_SEXO@CDB_LINK ON C##DM_ACADEMICO.F_MATRICULA@CDB_LINK(ID_SEXO)';
    DBMS_OUTPUT.PUT_LINE('Índices creados exitosamente');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error creando índices: ' || SQLERRM);
END;
/

PROMPT ¡Copia completada! Ahora puedes configurar Pentaho con:
PROMPT Host: localhost
PROMPT Database: XE  
PROMPT User: C##DM_ACADEMICO
PROMPT Password: dm_academico
